SELECT
  a.CARRY_OUT_DIST_BASE_CD 搬出物流拠点コード,
  b.DIST_BASE_NAME 搬出物流拠点名,
  a.CARRY_IN_DIST_BASE_CD 搬入物流拠点コード,
  c.DIST_BASE_NAME 搬入物流拠点名,
  a.DELI_LT 配送リードタイム,
  a.M_INVALID_FLG マスタ無効フラグ,
  a.CREATED_BY_ID 作成者ID,
  a.CREATE_DATETIME 作成日時,
  a.LAST_UPDATED_BY_ID 最終更新者ID,
  a.LAST_UPDATE_DATETIME 最終更新日時
FROM
  TJFAX66A_DIST_BASE_LT_M a,
  TJFAX641_DIST_BASE_M b,
  TJFAX641_DIST_BASE_M c
WHERE
  a.CARRY_OUT_DIST_BASE_CD = b.DIST_BASE_CD AND 
  a.CARRY_IN_DIST_BASE_CD = c.DIST_BASE_CD
ORDER BY a.CARRY_OUT_DIST_BASE_CD,a.CARRY_IN_DIST_BASE_CD
