SELECT DISTINCT
A.inv_grp_cd 在庫区コード
,C.INV_GRP_NAME 在庫区名
,A.area_cd エリアコード
,B.area_NAME エリア名
,A.DELI_PATTERN_CD 配送パターンコード
,D.DELI_PATTERN_NAME 配送パターン名
FROM TJFAX66C_DELIV_PT_JUDG_M A
  ,TJFAX661_AREA_M b
  ,TJFCX511_INV_GRP_M C
  ,TJFAX666_DELIV_PATTERN_M D
WHERE A.M_INVALID_FLG='0'
 AND B.M_INVALID_FLG='0'
 AND C.M_INVALID_FLG='0'
 AND D.M_INVALID_FLG='0'
 AND A.inv_grp_cd=C.inv_grp_cd
 AND A.area_cd=B.area_cd
 AND A.DELI_PATTERN_CD=D.DELI_PATTERN_CD
 AND LENGTH(A.inv_grp_cd)=3
 AND C.VO3IS_CONTROL_FLG='1'
 ORDER BY 1,3,5
