set echo on
--■注文書番号を抽出する
set echo on
SELECT 
substrb( UTL_I18N.RAW_TO_CHAR(DBMS_LOB.SUBSTR(A.BASE_MESSAGE_RAW_DATA,2000,1),'AL32UTF8'), INSTRB(UTL_I18N.RAW_TO_CHAR(DBMS_LOB.SUBSTR(A.BASE_MESSAGE_RAW_DATA,2000,1),'AL32UTF8'),'<prIrNum')+9,INSTRB(UTL_I18N.RAW_TO_CHAR(DBMS_LOB.SUBSTR(A.BASE_MESSAGE_RAW_DATA,2000,1),'AL32UTF8'),'</prIrNum>')-INSTRB(UTL_I18N.RAW_TO_CHAR(DBMS_LOB.SUBSTR(A.BASE_MESSAGE_RAW_DATA,2000,1),'AL32UTF8'),'<prIrNum')-9) as エラーメッセージ
FROM TJFTX001_MESSAGE_HISTORY a
WHERE a.BASE_UNIQUE_ID in (
'【置換文字列1】'
);

--■注文書番号から、対象の問合せ番号を特定する
select distinct C.ir_doc_num,b.inquiry_num,a.pr_arrange_num,b.cr_item_cd,b.cr_item_name,b.DIST_PROGRESS_STATUS from TJFAX331_PR_ARRANGE a ,TJFAX15A_CR_ITEM b,TJFEX011_PR_RECEIPT C
where C.ir_doc_num in (
'QV1039S6'
)
and a.cr_num=b.cr_num
and a.PR_ARRANGE_NUM=C.PR_NUM
--and b.l_flg='1' and b.cancel_flg='0'
order by 1,2
;


--■問合せ番号→他社仕入依頼番号を特定する
select * from TJFEX018_OTHCOM_PURC_L where substr(OC_PURC_COOP_IR_NUM,1,11) in (
'JS380249011'
);

--■他社仕入依頼番号→リカバリ対象を特定する
--select * from TJFEX019_OTHCOM_PURC_L_HIST;
select OC_PURC_REQ_NUM,OC_PURC_L_NUM,max(OC_PURC_LINE_HIST_NUM) from TJFEX019_OTHCOM_PURC_L_HIST where OC_PURC_REQ_NUM in (
'AGK100000738421'
)
group by OC_PURC_REQ_NUM,OC_PURC_L_NUM;
--▼
select OC_PURC_REQ_NUM,PR_ARRANGE_NUM,OC_PURC_L_NUM,OC_PURC_LINE_HIST_NUM,PR_ARRANGE_NUM from TJFEX019_OTHCOM_PURC_L_HIST
where OC_PURC_REQ_NUM in (
'AGK100000738421'
)
and OC_PURC_LINE_HIST_NUM=99;

--■■■■■更新■■■■■
--■他社仕入明細履歴：履歴３を最新にする→３～９８を論理削除する
UPDATE TJFEX019_OTHCOM_PURC_L_HIST SET OC_PURC_REQ_NUM='B'||substr(OC_PURC_REQ_NUM,2,14),PR_ARRANGE_NUM='B'||substr(PR_ARRANGE_NUM,2,14) 
 WHERE (OC_PURC_REQ_NUM,OC_PURC_L_NUM) in (
('AGK100000738421',3)
)
AND OC_PURC_LINE_HIST_NUM between 3 and 98;
--▼論理削除確認
select OC_PURC_REQ_NUM,OC_PURC_L_NUM,OC_PURC_LINE_HIST_NUM,PR_ARRANGE_NUM from TJFEX019_OTHCOM_PURC_L_HIST
 WHERE (OC_PURC_REQ_NUM,OC_PURC_L_NUM) in (
('AGK100000738421',3)
)
AND OC_PURC_LINE_HIST_NUM between 3 and 98
ORDER BY OC_PURC_REQ_NUM,OC_PURC_L_NUM,OC_PURC_LINE_HIST_NUM;

--■他社仕入明細履歴：履歴９９を３にする
UPDATE TJFEX019_OTHCOM_PURC_L_HIST SET OC_PURC_LINE_HIST_NUM = 3
 WHERE (OC_PURC_REQ_NUM,OC_PURC_L_NUM) in (
('AGK100000738421',3)
)
AND OC_PURC_LINE_HIST_NUM = 99;

--■他社仕入明細：最新を３にする
update TJFEX018_OTHCOM_PURC_L set OTHCOM_PURC_L_LAST_HIST_NUM=3
 WHERE (OC_PURC_REQ_NUM,OC_PURC_L_NUM) in (
('AGK100000738421',3)
);



--■更新後確認
--■他社仕入明細履歴：履歴９９が存在しないことを確認
select OC_PURC_REQ_NUM,PR_ARRANGE_NUM,OC_PURC_L_NUM,OC_PURC_LINE_HIST_NUM,PR_ARRANGE_NUM from TJFEX019_OTHCOM_PURC_L_HIST
where OC_PURC_REQ_NUM in (
'AGK100000738421'
)
and OC_PURC_LINE_HIST_NUM in (3,99);

--■他社仕入明細：最新履歴（OTHCOM_PURC_L_LAST_HIST_NUM）が３になっていることを確認
select OC_PURC_REQ_NUM,OC_PURC_L_NUM,CR_NUM,CR_L_NUM,CR_LINE_HIST_NUM,OTHCOM_PURC_L_LAST_HIST_NUM from TJFEX018_OTHCOM_PURC_L where OC_PURC_REQ_NUM in (
'AGK100000738421'
);
--commit;










