SET ECHO ON
--■受注商品明細
--▼出荷指示日更新
SELECT CR_NUM,CR_L_NUM,CR_LINE_HIST_NUM,SHIPPING_SPC_DATE FROM TJFAX15A_CR_ITEM WHERE CR_NUM='【置換文字列1】' AND L_FLG=1;
UPDATE TJFAX15A_CR_ITEM set SHIPPING_SPC_DATE='【置換文字列2】'                        WHERE CR_NUM='【置換文字列1】' AND CR_L_NUM= ★ AND CR_LINE_HIST_NUM=1 AND L_FLG='1';


--■出荷配送手配
SELECT SHIPPING_DELI_ARRANGE_NUM,SHIP_DELI_ARR_H_NUM,SHIPPING_SPC_DATE,SHIP_DELI_ARR_STATUS FROM TJFAX341_SHIP_DELIV_ARRANGE WHERE DELI_REQ_MGMT_NUM='【置換文字列3】' AND L_FLG='1';

--▼出荷指示日更新
UPDATE TJFAX341_SHIP_DELIV_ARRANGE set SHIPPING_SPC_DATE='【置換文字列2】' WHERE (SHIPPING_DELI_ARRANGE_NUM='★' AND SHIP_DELI_ARR_H_NUM=1);

--▼再連携
UPDATE TJFAX341_SHIP_DELIV_ARRANGE set SHIP_DELI_ARR_STATUS='10' WHERE DELI_REQ_MGMT_NUM='【置換文字列3】' AND L_FLG='1';

--commit;


