SET ECHO ON
SELECT INQUIRY_NUM,CR_NUM,CR_L_NUM,CR_LINE_HIST_NUM,DELI_SERV_CTGR,ASSORT_BEFORE_DELI_SERV_CTGR,CARRY_OUT_DIST_BASE_CD,CARRY_OUT_DIST_BASE_NAME,DELI_DIST_BASE_CD,DELI_DIST_BASE_NAME FROM TJFAX15A_CR_ITEM
 WHERE CR_NUM ='【置換文字列1】' AND CR_L_NUM =【置換文字列2】 AND CR_LINE_HIST_NUM=【置換文字列3】;

--配送サービス区分を「マシン」→「混載」、配送物流拠点コード、配送物流拠点名を、搬出物流拠点コード、搬出物流拠点名　に合わせる
UPDATE TJFAX15A_CR_ITEM SET DELI_DIST_BASE_CD=CARRY_OUT_DIST_BASE_CD,DELI_DIST_BASE_NAME=CARRY_OUT_DIST_BASE_NAME,DELI_SERV_CTGR='14'
WHERE CR_NUM ='【置換文字列1】' AND CR_L_NUM =【置換文字列2】 AND CR_LINE_HIST_NUM=【置換文字列3】;

--Commit;

--■以下は戻しが発生した場合に使用する
--配送サービス区分を「混載」→「マシン」、配送物流拠点コード、配送物流拠点名を元の値に戻して、カラ更新する
UPDATE TJFAX15A_CR_ITEM SET DELI_DIST_BASE_CD='★４',DELI_DIST_BASE_NAME='★５',DELI_SERV_CTGR='13'
WHERE CR_NUM ='【置換文字列1】' AND CR_L_NUM =【置換文字列2】 AND CR_LINE_HIST_NUM=【置換文字列3】;
