
--éÛíçî¿ì¸èoñæç◊É^Éuï∂éöç¨ì¸É`ÉFÉbÉN(RSÅACONFIGòAågílïsê≥)
set echo on

--Å°éÛíçî¿ì¸èoñæç◊
select CR_NUM,
DELIVERY_REQ_NUM,
replace(CARRY_IN_CUST_ENT_NAME,CHR(9),'\t'),
replace(CARRY_IN_CUST_EST_NAME,CHR(9),'\t'),
replace(CARRY_IN_CUST_DEPNAME,CHR(9),'\t'),
replace(CARRY_OUT_CUST_ENTERPRISE_NAME,CHR(9),'\t'),
replace(CARRY_OUT_CUST_EST_NAME,CHR(9),'\t'),
replace(CARRY_OUT_CUST_DEPNAME,CHR(9),'\t'),
replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),'\t'),
replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),'\t'),
replace(INSTALL_TO_DEPNAME,CHR(9),'\t')
from TJFAX157_CR_DELIV
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','');

update TJFAX157_CR_DELIV set
CARRY_IN_CUST_ENT_NAME         = replace(CARRY_IN_CUST_ENT_NAME,CHR(9),''),
CARRY_IN_CUST_EST_NAME         = replace(CARRY_IN_CUST_EST_NAME,CHR(9),''),
CARRY_IN_CUST_DEPNAME          = replace(CARRY_IN_CUST_DEPNAME,CHR(9),''),
CARRY_OUT_CUST_ENTERPRISE_NAME = replace(CARRY_OUT_CUST_ENTERPRISE_NAME,CHR(9),''),
CARRY_OUT_CUST_EST_NAME        = replace(CARRY_OUT_CUST_EST_NAME,CHR(9),''),
CARRY_OUT_CUST_DEPNAME         = replace(CARRY_OUT_CUST_DEPNAME,CHR(9),''),
INSTALL_TO_ENTERPRISE_NAME     = replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),''),
INSTALL_TO_ESTABLISHMENT_NAME  = replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),''),
INSTALL_TO_DEPNAME             = replace(INSTALL_TO_DEPNAME,CHR(9),'')
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','')
--and DELIVERY_REQ_NUM = 1
;

select CR_NUM,
DELIVERY_REQ_NUM,
replace(CARRY_IN_CUST_ENT_NAME,CHR(9),'\t'),
replace(CARRY_IN_CUST_EST_NAME,CHR(9),'\t'),
replace(CARRY_IN_CUST_DEPNAME,CHR(9),'\t'),
replace(CARRY_OUT_CUST_ENTERPRISE_NAME,CHR(9),'\t'),
replace(CARRY_OUT_CUST_EST_NAME,CHR(9),'\t'),
replace(CARRY_OUT_CUST_DEPNAME,CHR(9),'\t'),
replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),'\t'),
replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),'\t'),
replace(INSTALL_TO_DEPNAME,CHR(9),'\t')
from TJFAX157_CR_DELIV
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','');

--Å°çwîÉéÛït
select PR_NUM,
replace(CARRY_IN_CUST_ENT_NAME,CHR(9),'\t'),
replace(CARRY_IN_CUST_EST_NAME,CHR(9),'\t'),
replace(CARRY_IN_CUST_DEPNAME,CHR(9),'\t'),
replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),'\t'),
replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),'\t'),
replace(INSTALL_TO_DEPNAME,CHR(9),'\t'),
replace(FIRST_DLVRY_TO_SECT_NAME,CHR(9),'\t'),
replace(FIRST_DLVRY_TO_CUST_DEPNAME,CHR(9),'\t')
from TJFEX011_PR_RECEIPT
where inquiry_num in ('Åyíuä∑ï∂éöóÒ2Åz','','');

update TJFEX011_PR_RECEIPT set
CARRY_IN_CUST_ENT_NAME        = replace(CARRY_IN_CUST_ENT_NAME,CHR(9),''),
CARRY_IN_CUST_EST_NAME        = replace(CARRY_IN_CUST_EST_NAME,CHR(9),''),
CARRY_IN_CUST_DEPNAME         = replace(CARRY_IN_CUST_DEPNAME,CHR(9),''),
INSTALL_TO_ENTERPRISE_NAME    = replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),''),
INSTALL_TO_ESTABLISHMENT_NAME = replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),''),
INSTALL_TO_DEPNAME            = replace(INSTALL_TO_DEPNAME,CHR(9),''),
FIRST_DLVRY_TO_SECT_NAME      = replace(FIRST_DLVRY_TO_SECT_NAME,CHR(9),''),
FIRST_DLVRY_TO_CUST_DEPNAME   = replace(FIRST_DLVRY_TO_CUST_DEPNAME,CHR(9),'')
where inquiry_num in ('Åyíuä∑ï∂éöóÒ2Åz','','');

select PR_NUM,
replace(CARRY_IN_CUST_ENT_NAME,CHR(9),'\t'),
replace(CARRY_IN_CUST_EST_NAME,CHR(9),'\t'),
replace(CARRY_IN_CUST_DEPNAME,CHR(9),'\t'),
replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),'\t'),
replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),'\t'),
replace(INSTALL_TO_DEPNAME,CHR(9),'\t'),
replace(FIRST_DLVRY_TO_SECT_NAME,CHR(9),'\t'),
replace(FIRST_DLVRY_TO_CUST_DEPNAME,CHR(9),'\t')
from TJFEX011_PR_RECEIPT
where inquiry_num in ('Åyíuä∑ï∂éöóÒ2Åz','','');
*/

--Å°éÛíççÏã∆ñæç◊
select CR_NUM,
CR_L_NUM,
CR_LINE_HIST_NUM,
replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),'\t'),
replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),'\t'),
replace(INSTALL_TO_DEPNAME,CHR(9),'\t')
from TJFAX15G_CR_SERVICE_LINE
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','');

update TJFAX15G_CR_SERVICE_LINE set
INSTALL_TO_ENTERPRISE_NAME     = replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),''),
INSTALL_TO_ESTABLISHMENT_NAME  = replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),''),
INSTALL_TO_DEPNAME             = replace(INSTALL_TO_DEPNAME,CHR(9),'')
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','');

select CR_NUM,
CR_L_NUM,
CR_LINE_HIST_NUM,
replace(INSTALL_TO_ENTERPRISE_NAME,CHR(9),'\t'),
replace(INSTALL_TO_ESTABLISHMENT_NAME,CHR(9),'\t'),
replace(INSTALL_TO_DEPNAME,CHR(9),'\t')
from TJFAX15G_CR_SERVICE_LINE
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','');

--Å°éÛíç
select CR_NUM,
replace(SALES_TO_ENTERPRISE_NAME,CHR(9),'\t'),
replace(SALES_TO_ESTABLISHMENT_NAME,CHR(9),'\t'),
replace(SALES_TO_DEPNAME,CHR(9),'\t')
from TJFAX151_CUSTOMER_REQUEST
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','');

update TJFAX151_CUSTOMER_REQUEST set
SALES_TO_ENTERPRISE_NAME     = replace(SALES_TO_ENTERPRISE_NAME,CHR(9),''),
SALES_TO_ESTABLISHMENT_NAME  = replace(SALES_TO_ESTABLISHMENT_NAME,CHR(9),''),
SALES_TO_DEPNAME             = replace(SALES_TO_DEPNAME,CHR(9),'')
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','');

select CR_NUM,
replace(SALES_TO_ENTERPRISE_NAME,CHR(9),'\t'),
replace(SALES_TO_ESTABLISHMENT_NAME,CHR(9),'\t'),
replace(SALES_TO_DEPNAME,CHR(9),'\t')
from TJFAX151_CUSTOMER_REQUEST
where cr_num in ('Åyíuä∑ï∂éöóÒ1Åz','','');
