--受注搬入出明細タブ文字混入チェック(RS、CONFIG連携値不正)
set echo on

--■■■受注搬入出明細■■■
select CR_NUM,DELIVERY_REQ_NUM,CARRY_IN_CUST_ENT_NAME,CARRY_OUT_CUST_ENTERPRISE_NAME,CARRY_IN_CUST_EST_NAME,CARRY_OUT_CUST_EST_NAME,INSTALL_TO_DEPNAME from TJFAX157_CR_DELIV
where cr_num in ('【置換文字列1】','','');

update TJFAX157_CR_DELIV set
--CARRY_IN_CUST_ENT_NAME         = '近文事務所',
--CARRY_OUT_CUST_ENTERPRISE_NAME            = '近文事務所',
--CARRY_IN_CUST_EST_NAME         = '近文事務所',
--CARRY_OUT_CUST_EST_NAME        = 'ワールド宇田川ビル',
--INSTALL_TO_DEPNAME = '近文事務所',
    LAST_UPDATED_BY_ID = 'g10012013',
    LAST_UPDATE_DATETIME = sysdate
where cr_num ='【置換文字列1】' and DELIVERY_REQ_NUM = 1;

select CR_NUM,DELIVERY_REQ_NUM,    CARRY_IN_CUST_ENT_NAME,CARRY_OUT_CUST_ENTERPRISE_NAME,CARRY_IN_CUST_EST_NAME,CARRY_OUT_CUST_EST_NAME,INSTALL_TO_DEPNAME from TJFAX157_CR_DELIV
where cr_num in ('【置換文字列1】','','');


--■■■購買受付■■■
select PR_NUM,CARRY_IN_CUST_DEPNAME,INSTALL_TO_DEPNAME,CARRY_IN_CUST_EST_NAME,INSTALL_TO_ESTABLISHMENT_NAME from TJFEX011_PR_RECEIPT
where inquiry_num in ('【置換文字列2】','','');

select PR_NUM,CARRY_IN_CUST_DEPNAME,INSTALL_TO_DEPNAME,CARRY_IN_CUST_EST_NAME,INSTALL_TO_ESTABLISHMENT_NAME
from TJFEX011_PR_RECEIPT where PR_NUM in ('★★★','','');

update TJFEX011_PR_RECEIPT set
--CARRY_IN_CUST_DEPNAME         = '近文事務所',
--INSTALL_TO_DEPNAME            = '近文事務所',
--CARRY_IN_CUST_EST_NAME        = '近文事務所',
--INSTALL_TO_ESTABLISHMENT_NAME = '近文事務所',
    LAST_UPDATED_BY_ID = 'g10012013',
    LAST_UPDATE_DATETIME = sysdate
where PR_NUM in ('★★★','','');

select PR_NUM,CARRY_IN_CUST_DEPNAME,INSTALL_TO_DEPNAME,CARRY_IN_CUST_EST_NAME,INSTALL_TO_ESTABLISHMENT_NAME from TJFEX011_PR_RECEIPT
where PR_NUM in ('★★★','','');

--■■■受注作業明細■■■
select CR_NUM,CR_L_NUM,CR_LINE_HIST_NUM,     INSTALL_TO_DEPNAME,INSTALL_TO_ESTABLISHMENT_NAME   from TJFAX15G_CR_SERVICE_LINE
where cr_num in ('【置換文字列1】','','');

update TJFAX15G_CR_SERVICE_LINE set
--INSTALL_TO_DEPNAME = '近文事務所',
--INSTALL_TO_ESTABLISHMENT_NAME = 'ワールド宇田川ビル',
    LAST_UPDATED_BY_ID = 'g10012013',
    LAST_UPDATE_DATETIME = sysdate
where cr_num in ('【置換文字列1】','','');


select CR_NUM,CR_L_NUM,CR_LINE_HIST_NUM,INSTALL_TO_DEPNAME,INSTALL_TO_ESTABLISHMENT_NAME from TJFAX15G_CR_SERVICE_LINE
where cr_num in ('【置換文字列1】','','');

--commit;

