--■依頼元課所コードが古い→最新化
----▼パターン１　依頼元課所コードの場合  依頼元課所コード更新

set echo on
SELECT CR_NUM,SRC_OF_REQ_CUBIC_DEPT_CD,SRC_OF_REQ_SECT_CD FROM TJFAX151_CUSTOMER_REQUEST WHERE CR_NUM='【置換文字列1】';
SELECT SECT_CD,VALID_START_DATETIME,VALID_END_DATETIME FROM TJFXX04E_ORG_BASIC_M WHERE CUBIC_DEPT_CD='★' ORDER BY VALID_START_DATETIME;
UPDATE TJFAX151_CUSTOMER_REQUEST SET SRC_OF_REQ_SECT_CD='★' WHERE CR_NUM='【置換文字列1】';
SELECT CR_NUM,SRC_OF_REQ_CUBIC_DEPT_CD,SRC_OF_REQ_SECT_CD FROM TJFAX151_CUSTOMER_REQUEST WHERE CR_NUM='【置換文字列1】';
--COMMIT;


----▼パターン２　売上課所コードの場合
set echo on
SELECT CR_NUM,SALES_CUBIC_DEPT_CD,SALES_SECT_CD FROM TJFAX151_CUSTOMER_REQUEST WHERE CR_NUM='【置換文字列1】';
SELECT SECT_CD,VALID_START_DATETIME,VALID_END_DATETIME FROM TJFXX04E_ORG_BASIC_M WHERE CUBIC_DEPT_CD='★' ORDER BY VALID_START_DATETIME;
UPDATE TJFAX151_CUSTOMER_REQUEST SET SALES_SECT_CD='★' WHERE CR_NUM='【置換文字列1】';
SELECT CR_NUM,SALES_CUBIC_DEPT_CD,SALES_SECT_CD FROM TJFAX151_CUSTOMER_REQUEST WHERE CR_NUM='【置換文字列1】';
--COMMIT;




