@%OneDrive%\ツール\１．コマンド実行\Ｚ．共通\共通設定.sql

SET ECHO OFF 

set heading off

SELECT '----▼キッティング出荷指示未連携リスト' FROM DUAL;

set heading oN

SELECT
  c.cr_item_cd|| ',' ||
  c.CR_QTY|| '個,' ||
  c.LINE_ALLOC_RESULT_CTGR|| ':注残,' ||
--  (select INV_QTY from TJFCX011_INV_QTY where ITEM_CD=c.cr_item_cd and INV_GRP_CD=c.ALLOC_INV_GRP_CD and INV_COND_CTGR='121')|| ',' ||
  b.CREATE_DATETIME|| ',' ||
  a.INQUIRY_NUM|| ',' ||
  a.KITTING_REQ_NUM|| ',' ||
  b.SHIPPING_SPC_DATE|| ',' ||
  b.SHIPPING_PLANED_DATE|| ',' ||
  a.FIXED_AFTER_DS_DATE
FROM
  TJFAX353_F_KIT_ACT a,
  TJFAX359_F_KIT_ACT_LINE b,
  TJFAX15A_CR_ITEM c
WHERE
    a.FACTORY_KITTING_ARRANGE_NUM = b.FACTORY_KITTING_ARRANGE_NUM
and a.FT_KIT_ARR_H_NUM = b.FT_KIT_ARR_H_NUM
and a.INQUIRY_NUM = c.INQUIRY_NUM
and b.INQUIRY_L_NUM = c.INQUIRY_L_NUM
and b.SHIPPING_SPC_DATE between to_char(sysdate-5,'YYYYMMDD') and to_char(sysdate,'YYYYMMDD')
and c.CANCEL_FLG = '0'
and c.L_FLG = '1'
--and c.KITTING_REQ_NUM is not null
--and c.FIXED_AFTER_DS_DATE is null
and c.LINE_ALLOC_RESULT_CTGR <> '12'
and c.LINE_ALLOC_RESULT_CTGR='13'
group by
  b.SHIPPING_SPC_DATE,
  b.CREATE_DATETIME,
  a.INQUIRY_NUM,
  a.KITTING_REQ_NUM,
  b.SHIPPING_PLANED_DATE,
  a.FIXED_AFTER_DS_DATE,
  c.cr_item_cd,
    c.LINE_ALLOC_RESULT_CTGR,
    c.CR_QTY
order by
  b.SHIPPING_SPC_DATE,
  b.CREATE_DATETIME,
  a.INQUIRY_NUM,
  a.KITTING_REQ_NUM,
  b.SHIPPING_PLANED_DATE,
  a.FIXED_AFTER_DS_DATE
;

set heading off

SELECT '----▼キッティング品種変更未送リスト' FROM DUAL;

set heading oN

select 
TJFAX15A.ALLOC_INV_GRP_CD||CHR(9)||
TJFAX15A.CR_ITEM_CD||CHR(9)||
TJFAX354.ITEM_CHG_BEFORE_ITEM_CD||CHR(9)||
sum(TJFAX354.ITEM_CHG_BEFORE_QTY) 必要数量
from
TJFAX353_F_KIT_ACT TJFAX353,
TJFAX359_F_KIT_ACT_LINE TJFAX359,
TJFAX354_F_KIT_ACT_ITM_CHG TJFAX354,
TJFAX351_F_KIT TJFAX351,
TJFAX352_F_KIT_LINE TJFAX352,
TJFAX15A_CR_ITEM TJFAX15A
where TJFAX353.FACTORY_KITTING_ARRANGE_NUM = TJFAX359.FACTORY_KITTING_ARRANGE_NUM
AND TJFAX353.FT_KIT_ARR_H_NUM = TJFAX359.FT_KIT_ARR_H_NUM
AND TJFAX359.FACTORY_KITTING_ARRANGE_NUM = TJFAX354.FACTORY_KITTING_ARRANGE_NUM
AND TJFAX359.FT_KIT_ARR_H_NUM = TJFAX354.FT_KIT_ARR_H_NUM
AND TJFAX359.FT_KIT_ARR_ITEM_CHG_L_NUM = TJFAX354.FT_KIT_ARR_ITEM_CHG_L_NUM
AND TJFAX353.FACTORY_KITTING_ARRANGE_NUM = TJFAX351.FACTORY_KITTING_ARRANGE_NUM
AND TJFAX353.FT_KIT_ARR_H_NUM = TJFAX351.FT_KIT_ARR_H_NUM
AND TJFAX351.FACTORY_KITTING_ARRANGE_NUM = TJFAX352.FACTORY_KITTING_ARRANGE_NUM
AND TJFAX351.FT_KIT_ARR_H_NUM = TJFAX352.FT_KIT_ARR_H_NUM
AND TJFAX351.L_FLG = '1' 
AND TJFAX351.CANCEL_FLG = '0' 
AND TJFAX352.CR_NUM = TJFAX15A.CR_NUM
AND TJFAX352.CR_L_NUM = TJFAX15A.CR_L_NUM
AND TJFAX352.CR_LINE_HIST_NUM = TJFAX15A.CR_LINE_HIST_NUM
AND not exists(select 'X' from TJFCX091_ITEM_CHG_REQ TJFCX091
  WHERE TJFAX15A.CR_NUM = TJFCX091.ITEM_CHG_SRC_OF_REQ_CR_NUM
  AND TJFAX15A.CR_L_NUM = TJFCX091.ITEM_CHG_SRC_OF_REQ_CR_L_NUM
  AND TJFAX15A.CR_LINE_HIST_NUM = TJFCX091.ITEM_CHG_SRC_REQ_CR_LINE_H_NUM
)
AND TJFAX359.MODEL_ITEM_CTGR_ID_FLG = '1'
AND TJFAX15A.DELIVERY_REQ_CTGR IN ('10','11')
AND TJFAX359.INQUIRY_L_NUM = TJFAX15A.INQUIRY_L_NUM
AND (NOT TJFAX354.ITEM_CHG_BEFORE_ITEM_CD IN ('515430','515429','515536','515534','308734','308827','308638','308732','308844','308573','308733'))
--AND TJFAX15A.LINE_ALLOC_RESULT_CTGR <> '12'
AND TJFAX359.SHIPPING_SPC_DATE between to_char(sysdate,'YYYYMMDD')-5 and to_char(sysdate,'YYYYMMDD')
group by 
TJFAX15A.ALLOC_INV_GRP_CD,
TJFAX15A.CR_ITEM_CD,
TJFAX354.ITEM_CHG_BEFORE_ITEM_CD
ORDER BY TJFAX15A.ALLOC_INV_GRP_CD,TJFAX354.ITEM_CHG_BEFORE_ITEM_CD
;


set heading off

SELECT '----▼FFM仕入入庫確認' FROM DUAL;
SELECT '受払在庫区コード,受払商品コード,受払処理日,受払数量,コメント' FROM DUAL;
SELECT '--------------------------------------------' FROM DUAL;
SELECT '"' ||
    STKIO_INV_GRP_CD  || '","' ||
    STKIO_ITEM_CD       || '","' ||
    STKIO_PROC_DATE         || '","' ||
    STKIO_QTY                 || '","' ||
    STKIO_ACT_CMMNT           || '"'
FROM TJFCX031_INV_STKIO_ACT WHERE INQUIRY_NUM LIKE 'HH%' AND STKIO_ACT_CMMNT LIKE '工場キッティング対応%' AND STKIO_PROC_DATE =TO_CHAR(SYSDATE,'YYYYMMDD') 
ORDER BY STKIO_INV_GRP_CD,STKIO_ITEM_CD,STKIO_QTY;

set heading oN

exit;
