@%OneDrive%\ツール\１．コマンド実行\Ｚ．共通\共通設定.sql


SELECT JOB_SUBMIT_NAME||','||JOB_EXECUTION_STATUS||','||JOB_INIT_SUBMIT_TIME||','||JOB_SUBMIT_ID||',★リラン時間→★'||JOB_EXECUTION_START_TIME FROM T_QUEUE_STATUS WHERE JOB_SUBMIT_NAME='&1';
exit;
