--■■当日発生したエラーの一覧を表示する■■
select 
CASE T_QUEUE_STATUS.JOB_EXECUTION_PROCESS_ID
    WHEN 'jfxappp71' THEN '１号機'
    WHEN 'jfxappp72' THEN '２号機'
    WHEN 'jfxappp73' THEN '３号機'
    ELSE '該当なし'
  END 号機,
   T_QUEUE_STATUS.JOB_SUBMIT_NAME           ,
   T_QUEUE_STATUS.JOB_ID                    ,
   M_JOB.JOB_NAME                           ,
   JOB_RESULT_DESCRIPTION                   ,
   T_QUEUE_STATUS.JOB_SUBMIT_ID             ,
   T_QUEUE_STATUS.JOB_JOB_SUBMIT_USER       ,
   T_QUEUE_STATUS.QUEUE_ID                  ,
   T_QUEUE_STATUS.JOB_PRIORITY              ,
   T_QUEUE_STATUS.JOB_INIT_SUBMIT_TIME      ,
   T_QUEUE_STATUS.JOB_EXECUTION_START_TIME  ,
   T_QUEUE_STATUS.JOB_EXECUTION_END_TIME    ,
   T_QUEUE_STATUS.JOB_EXECUTION_COUNT       ,
   T_QUEUE_STATUS.JOB_EXECUTION_COUNT_BY_STEP,
   T_QUEUE_STATUS.JOB_EXECUTION_STATUS      ,
   T_QUEUE_STATUS.BEFORE_JOB_SUBMIT_ID      ,
   T_QUEUE_STATUS.JOB_EXECUTION_PARAMETERS  ,
   T_QUEUE_STATUS.DESCRIPTION
from T_QUEUE_STATUS INNER JOIN M_JOB ON T_QUEUE_STATUS.JOB_ID = M_JOB.JOB_ID
LEFT JOIN T_JOB_RESULT ON T_QUEUE_STATUS.JOB_SUBMIT_ID = T_JOB_RESULT.JOB_SUBMIT_ID
where 1=1 
and  JOB_INIT_SUBMIT_TIME between TRUNC(SYSDATE) and SYSDATE 
AND JOB_EXECUTION_STATUS = 'Execution Failed'
AND T_QUEUE_STATUS.JOB_ID not in ('AJJFCXM054','AJJFDXM350','AJJFCXM032','AJJFCXM023','AJJFCXM021','AJJFCXM031','AJJFAXMC40','AJJFDXM750')
and not (T_QUEUE_STATUS.JOB_ID='AJJFDXM750' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%品種コードが商品基本情報マスタ、または販社商品情報マスタに存在しません。品種コード%')
and not (T_QUEUE_STATUS.JOB_ID='AJJFAXM051' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%データ・チェックで誤りが見つかりました。%')
and not (T_QUEUE_STATUS.JOB_ID='AJJFCXM024' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%データ・チェックで誤りが見つかりました。%')
and not (T_QUEUE_STATUS.JOB_ID='AJJFEXM011' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%データ・チェックで誤りが見つかりました。%')
and not (T_QUEUE_STATUS.JOB_ID='AJJFEXM510' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%データ・チェックで誤りが見つかりました。%')
and not (T_QUEUE_STATUS.JOB_ID='AJJFAXM320' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%データ・チェックで誤りが見つかりました。%')
and not (T_QUEUE_STATUS.JOB_ID='AJJFAXMMB2' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%データ・チェックで誤りが見つかりました。%')
and not (T_QUEUE_STATUS.JOB_ID='AJJFEXM510' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%データ・チェックで誤りが見つかりました。%')
and not (T_QUEUE_STATUS.JOB_ID='AJJFDXM582' and T_JOB_RESULT.JOB_RESULT_DESCRIPTION like '%汎用マスタ%')
order by 4 asc,1 asc